name: Check types
on:
    workflow_call: null
jobs:
    check-types:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout chidori@${{ github.ref }}
              uses: actions/checkout@v4
              with:
                repository: ${{ github.repository }}
                ref: ${{ github.ref }}
                fetch-depth: 2
            
            - name: Install Dependencies
              uses: ./tooling/github/setup
            
            - name: Typecheck Packages
              run: pnpm test